export enum EXCEPTION_CODES {
  CARD_NOT_FOUND,
  CARD_NUMBER_NOT_VALID,
  CARD_ALREADY_EXISTS,
  CARD_CVV_NOT_VALID,
  CARD_EMAIL_NOT_VALID,
  CARD_EXPIRATION_MONTH_NOT_VALID,
  CARD_EXPIRATION_YEAR_NOT_VALID,
  CARD_BUSINESS_NOT_VALID,
  CARD_TOKEN_EXPIRED,
  CARD_TOKEN_RETRIEVED_UNSUCCESFULLY
}
